tools:
  get-directory-tree:
    description: |
      Generate a directory tree with standard exclusions and gitignore support
      
      Examples:
        - get_directory_tree(directory="/path/to/project")  # basic usage with default exclusions
        - get_directory_tree(directory="/path/to/project", format_args="-L 3")  # limit depth to 3 levels
        - get_directory_tree(directory="/home/user/code", custom_excludes="|dist|build", format_args="-C --dirsfirst")  # custom exclusions with colorized output and directories first
    execution:
      command: >-
        tree '<<directory>>'
        -a --gitignore
        -I ".git|.claude|.env|.venv|env|node_modules|__pycache__|.DS_Store|*.pyc<<custom_excludes>>"
        <<format_args>>
    parameters:
      directory:
        description: Directory to generate tree for (quotes are handled automatically in the command)
        required: true
      custom_excludes:
        description: Additional patterns to exclude (begin with | e.g., "|build|dist"). Probably not needed if there is a .gitignore file.
        required: false
      format_args:
        description: Additional formatting arguments (e.g., "-L 3 -C --dirsfirst")
        required: false

  find-files:
    description: |
      Locate files by name, pattern, type, size, date, or other criteria
      
      Examples:
        - find_files(directory="/full/path/src", arguments="-name *.py")  # find all Python files
        - find_files(directory="/full/path/project", arguments="-mtime -7")  # find files modified in the last 7 days
        - find_files(directory="/full/path/data", arguments="-size +1M")  # find files larger than 1 MB
        - find_files(directory="/full/path/src", arguments="-name *.js -not -path */node_modules/*")  # find JS files excluding node_modules
    execution:
      command: >-
        find '<<directory>>' -type f <<arguments>> | sort
    parameters:
      directory:
        description: Directory to search in (quotes are handled automatically in the command)
        required: true
      arguments:
        description: Additional find arguments (e.g., "-name *.py -mtime -7 -not -path */venv/*")
        required: false

  find-text-patterns:
    description: |
      Find text patterns in files with optional context and filtering.

      Examples:
        - find_text_patterns(pattern="function", arguments="/full/path/directory --include=*.js")  # find "function" in JS files
        - find_text_patterns(pattern="TODO:", arguments="-i /full/path/src --include=*.py --include=*.js -B 2 -A 2")  # find TODOs case-insensitively with 2 lines of context before and after
        - find_text_patterns(pattern="import.*pandas", arguments="/full/path/src --include=*.py")  # find pandas imports in Python files
        - find_text_patterns(pattern="error", arguments="-i /full/path/logs -A 5")  # find errors case-insensitively with 5 lines after
    execution:
      command: >-
        grep -r --color=never '<<pattern>>' <<arguments>>
    parameters:
      pattern:
        description: Text pattern to search for (supports regex, quotes are handled automatically in the command)
        required: true
      arguments:
        description: Additional grep arguments (e.g., directory/files to search, "-i for case-insensitive, -A 3 for context, --include=*.py")
        required: false

  extract-file-text:
    description: |
      Display contents of a file with optional line numbers or filtering
      
      Examples:
        - extract_file_text(file="/path/to/script.py")  # view entire file with line numbers
        - extract_file_text(file="/path/to/script.py", arguments="| sed -n '10,20p'")  # view only lines 10-20
        - extract_file_text(file="/path/to/config.json", arguments="| python3 -m json.tool")  # pretty-print JSON file
        - extract_file_text(file="/path/to/error.log", arguments="| grep ERROR")  # filter file to show only ERROR lines
    execution:
      command: >-
        cat '<<file>>' <<arguments>> | nl -ba
    parameters:
      file:
        description: Path to the file to display (quotes are handled automatically in the command)
        required: true
      arguments:
        description: Additional processing options (e.g., "| sed -n '10,20p'" to show specific line range, "| python3 -m json.tool" to format JSON)
        required: false

  extract-code-info:
    description: |
      Extract and analyze code information (functions, classes, imports, etc.) from multiple files
      
      Examples:
        - extract_code_info(files="/path/to/script.py", types="functions")  # list functions in one file
        - extract_code_info(files="*.py", types="functions,classes")  # list functions and classes in all Python files
        - extract_code_info(files="src/*.js", types="imports,todos")  # show imports and TODOs in JavaScript files
    execution:
      command: >-
        for file in $(find <<files>> -type f 2>/dev/null || echo <<files>>); do
          if [ ! -f "$file" ]; then
            continue
          fi
          echo "=== File: $file ===";
          
          if [[ "<<types>>" == *"functions"* ]]; then
            echo "--- functions ---";
            grep -n "^[[:space:]]*def " "$file" || grep -n "function " "$file" || echo "No function definitions found";
          fi
          
          if [[ "<<types>>" == *"imports"* ]]; then
            echo "--- imports ---";
            grep -n "^[[:space:]]*import " "$file" || grep -n "^[[:space:]]*from " "$file" || grep -n "require(" "$file" || echo "No imports found";
          fi
          
          if [[ "<<types>>" == *"classes"* ]]; then
            echo "--- classes ---";
            grep -n "^[[:space:]]*class " "$file" || echo "No classes found";
          fi
          
          if [[ "<<types>>" == *"todos"* ]]; then
            echo "--- todos ---";
            grep -n -i "TODO\|FIXME" "$file" || echo "No TODOs found";
          fi
          
          echo "";
        done
    parameters:
      files:
        description: Path or pattern for code files to analyze (e.g., "src/*.py", or specific file path)
        required: true
      types:
        description: Comma-separated list of information types to extract (functions, classes, imports, todos)
        required: true
