tools:
  get-directory-tree:
    description: Generate a directory tree with standard exclusions and gitignore support
    execution:
      command: >-
        tree <<directory>> -a --gitignore -I ".git|.claude|.env|.venv|env|node_modules|__pycache__|.DS_Store|*.pyc<<custom_excludes>>" <<format_args>>
    parameters:
      directory:
        description: Directory to generate tree for
        required: true
      custom_excludes:
        description: Additional patterns to exclude (begin with | e.g., '|build|dist'). Probably not needed if there is a .gitignore file.
        required: false
      format_args:
        description: Additional formatting arguments (e.g., '-L 3 -C --dirsfirst')
        required: false
